services:
  spam-detection-api:
    image: ghcr.io/rifqiansharir/indobert-spam-detection-api:latest
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      interval: 5s
      timeout: 1m
      retries: 5
      start_period: 30s

  public-issue-classification-api:
    image: ghcr.io/rifqiansharir/indobert-public-issue-classification-api:latest
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')" ]
      interval: 5s
      timeout: 1m
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPAM_DETECTION_API_URL: http://spam-detection-api:8000/predict
      PUBLIC_ISSUE_CLASSIFICATION_API_URL: http://public-issue-classification-api:8000/predict
      SESSION_SECRET_KEY: ${SESSION_SECRET_KEY}
      USERDATA_DB_USER: ${USERDATA_DB_USER}
      USERDATA_DB_PASSWORD: ${USERDATA_DB_PASSWORD}
      USERDATA_DB_NAME: ${USERDATA_DB_NAME}
      USERDATA_DB_HOST: ${USERDATA_DB_HOST}
      USERDATA_DB_PORT: ${USERDATA_DB_PORT}
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      spam-detection-api:
        condition: service_healthy
      public-issue-classification-api:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/dist:/app/dist

volumes:
  userdata_db_data:
