[project]
name = "app"
version = "0.1.0"
description = "Backend for LaporMas"
authors = [{ name = "RifqiAnshari1", email = "rifqi.anshari@ui.ac.id" }]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.128.0",
    "uvicorn==0.47.0",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.13.4",
    "sqlmodel>=0.0.38",
    "sqladmin>=0.27.0",
    "itsdangerous>=2.2.0",
    "httpx>=0.28.1",
]

[project.scripts]
app = "app.main:main"

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 79             # PEP 8
target-version = "py312"
extend-exclude = ["*.ipynb"]

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]

[tool.ruff.format]
quote-style = "double"

[dependency-groups]
dev = ["ruff>=0.15.16"]

[tool.ruff.lint.isort]
force-sort-within-sections = true
