"""create_table

Revision ID: 090bb3f6b034
Revises:
Create Date: 2026-06-02 15:34:18.710800

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "090bb3f6b034"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "userdata",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("nik", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "message", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "PROCESS", "CLOSE", name="status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(
        op.f("ix_userdata_status"), "userdata", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_userdata_status"), table_name="userdata")
    op.drop_table("userdata")
    # ### end Alembic commands ###
